# Generated by Django 3.1.1 on 2020-10-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='Father_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
