# Generated by Django 3.1.1 on 2020-10-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201030_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Father_name',
            new_name='mobile',
        ),
    ]
