# Generated by Django 3.1.1 on 2020-10-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='possword',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], default='MALE', max_length=6),
        ),
    ]
