# Generated by Django 3.1.1 on 2020-11-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
