# Generated by Django 3.1.1 on 2020-11-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
