# Generated by Django 3.1.1 on 2020-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201102_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, default='demo.jpg', max_length=50, null=True),
        ),
    ]
