# Generated by Django 3.1.1 on 2020-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201102_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
