# Generated by Django 3.1.1 on 2020-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
